- hosts: "{{ host }}"
  serial: 1
  tasks:
    - name: include vault variables(proxmox cluster password)
      include_vars: 'vars/vault.yml'
      #no_log: true
    - name: Cloning a VM with Vm-id "{{ vmid }}" from a Proxmox VM template with VM-id "{{ template_vmid }}" on "{{ storage }}" storage "{{ api_host }}" host..
      proxmox_kvm:
        api_user    : root@pam
        api_password: "{{ proxmox_password }}"
        api_host    : "{{ api_host }}"
        clone       : "yes"
        newid       : "{{ vmid }}"
        vmid        : "{{ template_vmid }}"
        name        : "{{ name }}"
        node        : "{{ proxmox_node_name }}" 
        full        : "{{ full_clone }}"
        timeout     : "1190"
        skiplock    : 
      retries: 4
      delay: 15
    - name: Waiting a bit for the Hypervisor to catch up..
      pause:
        seconds: 4
