- name: Verify Ansible meets playbook's version requirements.
  assert:
    that: "ansible_version.full is version_compare('2.7.10', '>=')"
    msg: >
      "You must update your Ansible version to at least 2.7.10 to use this playbook safely"

- name: Install passlib python module 
  pip:
    name: passlib
    extra_args: --user

  #- name: "Check if passlib is installed"
  # package_facts:
  #  manager: "auto"

    #  - name: Assert that passlib_state_pip.state is present
    # assert:
    # that:
    #  - "((passlib_state_pip.state is defined) and ('present' in passlib_state_pip.state)) or ('passlib' in ansible_facts.packages)"
