- name: Install nfs-utils package
  package:
    name: nfs-utils
    state: present

- name: Creates nfsshare directory
  file:
    path: /mnt/nfs/var/nfsshare/jenkins-backup-data
    owner: jenkins
    group: jenkins
    state: directory

- name: Mount nfs share from QNAP store machine in the local subnet
  mount:
    path: /mnt/nfs/var/nfsshare
    src: "{{ nfs_source }}"
    fstype: nfs
    state: mounted
