---
# tasks file for sbaerlocher.qemu-guest-agent

- name: "windows : include sbaerlocher.virtio role"
  include_role:
    name: sbaerlocher.virtio
  tags:
    - packages

- name: "windows : install Qemu Guest Agent"
  win_package:
    path: "{{ virtio_win_iso_path }}\\guest-agent\\qemu-ga-x64.msi"
    creates_path: "{{ ansible_env['ProgramFiles'] }}\\qemu-ga"
  when: (ansible_virtio_version | default()) != virtio_version
  tags:
    - packages
