---
- hosts: localhost
  tasks:
    - name: include vault variables(proxmox cluster password)
      include_vars: 'vars/vault.yml'
      no_log: true
    - name: Create tmp folder
      file:
        path: ~/tmp
        state: directory
    - name: Scanning VM-id range ["{{ fromVmid }}" - "{{ toVmid }}"] for exising machines. Gathering and appending static Network-Address(Mac address)/IP entries to the DHCP section of the Perimeter router configuration file..
      script: get_vmid_and_mac_for_vmid_range.sh -s {{ api_host }} -p {{ proxmox_password }} -f {{ fromVmid }} -t {{ toVmid }} -m {{ internal_subnetmask }} -i {{ inventory_dir }} -d {{ playbook_dir }} 
      # no_log: true
    - name: Delete leftover files
      file:
        path: ~/tmp/proxvm-*.json
        state: absent
